name: Deploy Pelican Chat App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- Backend (Express) ---
      # If you only want to deploy the frontend UI for now, you can skip backend install.
      # Uncomment the next lines later when you package the API and UI together.
      # - name: Install backend deps
      #   working-directory: express-backend
      #   run: npm install --omit=dev --no-audit --no-fund

      # --- Frontend (build) ---
      - name: Build frontend
        working-directory: frontend
        run: |
          npm install --no-audit --no-fund
          npm run build

    # --- Package only the compiled UI ---
- name: Zip project
  run: |
    if [ -d "frontend/dist" ]; then
      cd frontend && zip -r ../app.zip dist
    elif [ -d "frontend/build" ]; then
      cd frontend && zip -r ../app.zip build
    else
      echo "No dist/build folder found after npm run build" && exit 1
    fi
